name: Build image and Push to ECR

# Quando houver um push nessa branch, você pode executar o job abaixo
on:
  push:
    branches:
      - main

permissions: 
  id-token: write
  contents: write
  issues: write
  pull-requests: write

jobs:
  build:
    name: 'Build and Push'
    runs-on: ubuntu-latest # Essa maquina ja tem docker instalado

    steps:
    - uses: actions/checkout@v4

    - name: Setup Node 
      uses: actions/setup-node@v4
      with:
        node-version: 20
        cache: 'npm'
    - run: npm install
    - run: npm run test

    - name: Generate tag based on commit hash
      id: generate_tag
      run: |
        SHA=$(echo $GITHUB_SHA | head -c7)
        echo "sha=$SHA" >> $GITHUB_OUTPUT

    - name: Configure Amazon AWS credentials
      uses: aws-actions/configure-aws-credentials@v4
      with:
        role-to-assume: arn:aws:iam::575108923772:role/ecr-role
        aws-region: us-east-2

    - name: Login to AWS ECR
      id: login-ecr
      uses: aws-actions/amazon-ecr-login@v2 

    - name: Build docker image and Push image to ECR
      id: build-docker-image
      env:
        REGISTRY: ${{ steps.login-ecr.outputs.registry }}
        TAG: ${{ steps.generate_tag.outputs.sha }}
      # Depois com push --all tags
      run: | 
        docker build -t $REGISTRY/nest-ci-api:$TAG .
        docker tag $REGISTRY/nest-ci-api:$TAG $REGISTRY/nest-ci-api:latest
        docker push --all-tags $REGISTRY/nest-ci-api:latest
        IMAGE=$(echo $REGISTRY/nest-ci-api:$TAG)
        echo "image=$IMAGE" >> $GITHUB_OUTPUT

